import os

CONTENT_DIR = os.path.join("content", "PCCST503")

# m1_01_ml_vs_traditional.md
m1_01 = """# Machine Learning vs Traditional Programming

**Why we stopped hand-writing rigid IF-ELSE rules and started letting computers deduce their own mathematical laws.**

<a id="the-intuition"></a>
## 1. The Intuition: Baking a Cake Without a Recipe

Imagine you want a computer to bake a delicious chocolate cake.

::: callout-intuition The Cake Analogy
- **In Traditional Programming:** You must provide both the **Data** (flour, sugar, eggs) and the exact, rigid **Rules** (*"Mix 2 eggs with 200g flour, bake at 350°F for exactly 30 minutes"*). If you follow the rules blindly, the computer outputs the Cake. But if someone wants a gluten-free mango cake tomorrow, *you* must manually sit down and write a completely new 50-step recipe.
- **In Machine Learning:** You have the raw **Data** (ingredients) and 1,000 photos/samples of award-winning **Outputs** (cakes), but you have *no clue* what the exact chemical recipe is. You feed both into the computer and ask: *"Find the mathematical patterns that turn these ingredients into those cakes!"* The computer analyses the relationships and outputs the **Rules (The Model)**.
:::

> **The Golden Paradigm Shift:**
> **Traditional Programming:** $\text{Data} + \text{Rules} \implies \text{Output}$
> **Machine Learning:** $\text{Data} + \text{Output} \implies \text{Rules (The Model)}$

---

<a id="the-math"></a>
## 2. Formal Paradigm Comparison

| Dimension | Traditional Programming (Deterministic) | Machine Learning (Inductive Learning) |
| :--- | :--- | :--- |
| **Primary Input** | Data + Explicit Hand-crafted Algorithm | Input Data ($X$) + Ground Truth Labels ($Y$) |
| **Core Output** | Computed Result / Action | A Generalizable Hypothesis / Model $h_\theta(x)$ |
| **Problem Domain** | Exact, well-defined logic (Tax calculators, Compilers) | Fuzzy, high-dimensional patterns (Vision, NLP, Diagnostics) |
| **Handling Edge Cases** | Requires humans to write hundreds of patch-rules | Model updates parameters $\theta$ automatically with new training data |
| **Mathematical Basis** | Boolean logic, deterministic state machines | Probability theory, linear algebra, calculus optimization |

::: callout-pitfall When NOT to use Machine Learning
Never use Machine Learning when exact, deterministic business rules already exist! For example, calculating GST/VAT (e.g. $\text{Tax} = \text{Total} \times 0.18$) should **always** be traditional code. Using ML to "guess" an invoice tax is slow, expensive, and legally hazardous.
:::

---

<a id="worked-example"></a>
## 3. Case Study: Building an Email Spam Filter

Let's walk through how this paradigm shift actually works when building a real-world system.

::: step [Step 1: The Goal] Define the Objective
Detect and block spam emails from reaching user inboxes without filtering out legitimate work emails.
:::

::: step [Step 2: The Traditional Flaw] The Game of Whack-A-Mole
A programmer writes a hardcoded rule: `IF text contains 'FREE CASH' THEN mark as Spam`. Spammers instantly adapt by writing `F-R-E-E C-A-S-H` or `Fr33 C@sh`. The programmer writes 1,000 extra rules. The codebase becomes an unmaintainable disaster.
:::

::: step [Step 3: The ML Dataset] Collecting Input & Output
We gather 20,000 historical emails ($X$) and label 10,000 as `Spam (y=1)` and 10,000 as `Not Spam (y=0)`.
:::

::: step [Step 4: Training & Convergence] Pattern Induction
An optimization algorithm analyzes word frequencies, header anomalies, and token embeddings. It assigns statistical weights $\theta$ to combinations of features without a single handwritten `IF` statement.
:::

---

<a id="simulation"></a>
## 4. Visualizing the Paradigm Shift

::: manim assets/videos/m1_paradigms.mp4 Paradigm Shift Architecture
Watch how the 'Rules' and 'Output' swap places in the software engineering pipeline.
:::

---

<a id="self-check"></a>
## 5. Active Recall Checkpoint

::: quiz Q1: Paradigm Foundations
In the Machine Learning paradigm, what is the primary output generated by the learning algorithm during training?
(A) The final prediction for a single user
(*B) The statistical rules / model parameters mapping inputs to outputs
(C) The raw database schema
(D) The compiled binary machine instructions
::: explanation
Unlike traditional software where human engineers write the rules to produce an output, ML algorithms take historical inputs and outputs to deduce the underlying mathematical rules (the Model $h_\theta(x)$).
:::

::: quiz Q2: Real-World Architecture
Which of the following problems is LEAST suitable for Machine Learning?
(A) Detecting credit card fraud from transaction patterns
(B) Transcribing spoken Malayalam voice notes into text
(*C) Calculating 18% GST on an e-commerce checkout cart
(D) Recommending relevant research papers to college students
::: explanation
Calculating tax is a strict, deterministic legal formula ($Total \times 0.18$). It requires 1 line of traditional code. Using ML introduces unnecessary statistical error, high compute cost, and unpredictable edge cases.
:::
"""

# m1_02_ml_paradigms.md
m1_02 = """# The 4 Learning Paradigms: How Computers Learn

**Supervised, Unsupervised, Semi-supervised, and Reinforcement Learning explained from zero.**

<a id="the-intuition"></a>
## 1. The Intuition: The 4 Ways Humans Learn

Just as humans learn through different teaching styles, algorithms are grouped into four primary learning paradigms based on the **presence and nature of feedback**.

::: callout-intuition Relatable Real-World Analogies
1. **Supervised Learning (Learning with an Answer Key):** A teacher gives you 1,000 flashcards. The front has a photo of an X-ray ($X$), and the back has the verified doctor's diagnosis ($Y$). You guess, check the back, and correct your mistakes.
2. **Unsupervised Learning (Finding Hidden Patterns):** You are given a bucket containing 10,000 mixed Lego bricks with zero labels or instructions. You naturally group them by color, shape, and size based purely on inherent similarity.
3. **Semi-Supervised Learning (The Guided Boost):** You have 100,000 medical scans, but doctors only had time to label 500 of them. You use the 500 labeled scans to anchor your knowledge, and the 99,500 unlabeled scans to understand overall structural variations.
4. **Reinforcement Learning (Trial, Error & Rewards):** A puppy learns to fetch a ball. If it brings the ball back, it gets a treat (+1 Reward). If it chews your shoe, it gets no treat (-1 Penalty). Over time, it learns the optimal policy to maximize treats.
:::

---

<a id="the-math"></a>
## 2. Mathematical Formalization

| Paradigm | Training Dataset Structure | Target Goal | Core Algorithms |
| :--- | :--- | :--- | :--- |
| **Supervised** | $\mathcal{D} = \{(x^{(i)}, y^{(i)})\}_{i=1}^m$ with known labels $y^{(i)}$ | Learn mapping $f: X \to Y$ minimizing empirical loss | Linear/Logistic Regression, SVM, Decision Trees, Neural Nets |
| **Unsupervised** | $\mathcal{D} = \{x^{(i)}\}_{i=1}^m$ (No target labels) | Discover latent structure $p(x)$ or cluster assignments | K-Means, Hierarchical Clustering, PCA, Autoencoders |
| **Semi-Supervised** | $\mathcal{D}_L \cup \mathcal{D}_U$ where $|\mathcal{D}_L| \ll |\mathcal{D}_U|$ | Exploit geometric density of unlabeled data to improve $f$ | Self-training, Pseudo-labeling, Graph-based SSL |
| **Reinforcement** | Environment states $s_t$, actions $a_t$, rewards $r_t$ | Maximize expected cumulative return $G_t = \sum \gamma^k r_{t+k+1}$ | Q-Learning, Policy Gradients (PPO), Deep Q-Networks (DQN) |

::: callout-formula Key Objective Functions
- **Supervised Empirical Risk:** $\min_\theta \frac{1}{m}\sum_{i=1}^m \mathcal{L}(h_\theta(x^{(i)}), y^{(i)})$
- **RL Bellman Optimality Equation:** $Q^*(s, a) = \mathbb{E}\left[ r + \gamma \max_{a'} Q^*(s', a') \right]$
:::

---

<a id="worked-example"></a>
## 3. Comparative Problem Solving

::: step [Scenario A: Housing Market] Supervised Regression
Given historical records of house square footage ($x_1$) and bedrooms ($x_2$), along with final sale price ($y$), train a regression model to predict continuous market prices for new listings.
:::

::: step [Scenario B: Customer Segmentation] Unsupervised Clustering
An e-commerce store has 1,000,000 user purchase logs but no demographic tags. Unsupervised clustering groups users into behavioral personas (e.g. "Weekend Bargain Hunters", "Tech Enthusiasts").
:::

::: step [Scenario C: AlphaGo & Robotics] Reinforcement Learning
A robotic arm attempts to balance a pole. Every second the pole remains upright yields a reward of $+1$. The agent iteratively optimizes its motor torque policy through continuous trial and error.
:::

---

<a id="simulation"></a>
## 4. Visualizing the Paradigms

::: manim assets/videos/m1_paradigms.mp4 The Four Learning Styles
Observe the difference between labeled classification boundaries and unsupervised cluster grouping.
:::

---

<a id="self-check"></a>
## 5. Active Recall Checkpoint

::: quiz Q1: Paradigm Identification
A bank wants to group its credit card customers into 5 distinct spending personas based on transaction histories, without any pre-existing category labels. Which paradigm must they use?
(A) Supervised Regression
(*B) Unsupervised Clustering
(C) Reinforcement Learning
(D) Semi-supervised Classification
::: explanation
Because there are no ground truth target labels provided ($y$), the algorithm must discover intrinsic geometric clusters in the transaction feature space on its own.
:::

::: quiz Q2: Reinforcement Learning Mechanics
In Reinforcement Learning, what guides the agent toward learning the optimal behavior policy?
(A) A human labeling every single state transition
(*B) A scalar reward signal (+/- feedback) from the environment
(C) Mean Squared Error calculated against a validation set
(D) Minimizing entropy across feature splits
::: explanation
RL agents learn by taking actions within an environment and updating their policy or value functions ($Q$-values) based on cumulative scalar rewards ($r_t$).
:::
"""

# m1_03_parameter_estimation_mle.md
m1_03 = """# Parameter Estimation: Maximum Likelihood Estimation (MLE)

**A rigorous way of answering: 'What underlying model parameter makes the data we observed the most probable?'**

<a id="the-intuition"></a>
## 1. The Intuition: The Biased Coin Detective

Imagine you find a mysterious coin on the street. You flip it **10 times**, and it lands on **Heads 7 times** and **Tails 3 times**.

::: callout-intuition The Core Question
You ask: *"What is the true probability $p$ that this coin lands on Heads?"*
- Could $p = 0.1$? (If it only gave heads 10% of the time, getting 7 heads would be miraculous).
- Could $p = 0.9$? (Possible, but getting 3 tails is somewhat unlikely).
- **Maximum Likelihood Estimation (MLE)** asks: *"Which specific value of $p \in [0, 1]$ maximizes the mathematical probability of observing exactly 7 Heads and 3 Tails?"*
:::

Common sense tells you $p = 0.7$. MLE is the exact calculus engine that proves your intuition is mathematically optimal!

---

<a id="the-math"></a>
## 2. Mathematical Derivation Step-by-Step

Let $X = \{x_1, x_2, \dots, x_n\}$ be independent and identically distributed (i.i.d.) observations from a Bernoulli distribution with parameter $p$:

$$ P(X=1) = p, \quad P(X=0) = 1-p $$

### Step 1: The Likelihood Function $L(p)$
Because the coin tosses are independent, the joint probability (Likelihood) of observing $k$ heads in $n$ tosses is the product of individual probabilities:

$$ L(p) = \prod_{i=1}^n P(x_i | p) = p^k (1-p)^{n-k} $$

### Step 2: The Log-Likelihood Trick ($\ell(p)$)
Multiplying hundreds of small probabilities (like $0.5 \times 0.5 \times \dots$) causes severe **numerical underflow** in computers. 

Since the natural logarithm $\ln(x)$ is a **strictly monotonic increasing function**, the parameter $p$ that maximizes $\ln(L(p))$ is identical to the parameter that maximizes $L(p)$:

$$ \ell(p) = \ln L(p) = \ln\left( p^k (1-p)^{n-k} \right) = k \ln(p) + (n-k) \ln(1-p) $$

### Step 3: Finding the Maximum via Calculus
To locate the peak of the log-likelihood curve, take the first derivative with respect to $p$ and set it to zero:

$$ \frac{d}{dp}\ell(p) = \frac{k}{p} - \frac{n-k}{1-p} = 0 $$

$$ \frac{k}{p} = \frac{n-k}{1-p} \implies k(1-p) = p(n-k) \implies k - kp = np - kp $$

$$ \hat{p}_{\text{MLE}} = \frac{k}{n} $$

::: callout-formula Parameter Decoder Table
| Symbol | Meaning | Example Value |
| :--- | :--- | :--- |
| $n$ | Total number of trials / samples | $10$ tosses |
| $k$ | Count of successful outcomes (Heads) | $7$ heads |
| $L(p)$ | Likelihood Function (Probability of data given $p$) | $p^7 (1-p)^3$ |
| $\ell(p)$ | Log-Likelihood (Converts product to sum) | $7\ln(p) + 3\ln(1-p)$ |
| $\hat{p}_{\text{MLE}}$ | Maximum Likelihood Estimator | $7/10 = 0.70$ |
:::

---

<a id="worked-example"></a>
## 3. Stepped Numerical Example

::: step [Step 1: Given Data] Problem Statement
A quality assurance engineer inspects $n=50$ microchips and finds $k=4$ defective chips. Find the Maximum Likelihood Estimate of the defect rate $p$.
:::

::: step [Step 2: Log-Likelihood Formulation] Setup Equation
$$ \ell(p) = 4 \ln(p) + (50 - 4) \ln(1-p) = 4 \ln(p) + 46 \ln(1-p) $$
:::

::: step [Step 3: First-Order Condition] Derivative
$$ \frac{d}{dp}\ell(p) = \frac{4}{p} - \frac{46}{1-p} = 0 \implies 4(1-p) = 46p $$
:::

::: step [Step 4: Analytical Solution] Final Result
$$ 4 = 50p \implies \hat{p}_{\text{MLE}} = \frac{4}{50} = 0.08 \text{ (8% Defect Rate)} $$
:::

---

<a id="simulation"></a>
## 4. Visualizing the Likelihood Hill

::: manim assets/videos/m1_paradigms.mp4 Likelihood Optimization Surface
Watch how the slope of the log-likelihood curve hits zero exactly at the maximum likelihood estimate.
:::

---

<a id="self-check"></a>
## 5. Active Recall Checkpoint

::: quiz Q1: Theoretical Motivation
Why do machine learning algorithms optimize the **Log-Likelihood** $\ln L(\theta)$ instead of the raw Likelihood $L(\theta)$?
(A) Logarithms change the location of the optimal parameter $\theta^*$
(*B) It converts numerically unstable products into stable sums and simplifies differentiation
(C) Logarithms guarantee the function is non-convex
(D) It eliminates the need for computing derivatives
::: explanation
Because probabilities are $\le 1$, multiplying thousands of them causes numerical underflow ($0.00000...$). Taking the logarithm transforms products into sums ($\ln(ab) = \ln a + \ln b$), while preserving the exact same argmax peak due to monotonicity.
:::

::: quiz Q2: Parameter Estimation
If you flip a coin 3 times and get 3 Heads ($n=3, k=3$), what is the Maximum Likelihood Estimate for $p$?
(A) 0.50
(B) 0.75
(*C) 1.00
(D) Undefined
::: explanation
$\hat{p}_{\text{MLE}} = \frac{k}{n} = \frac{3}{3} = 1.0$. This highlights a critical limitation of pure MLE: with small sample sizes, it completely overfits to the observed data, ignoring prior common sense that coins are usually fair. (This motivates MAP estimation!).
:::
"""

with open(os.path.join(CONTENT_DIR, "m1_01_ml_vs_traditional.md"), "w", encoding="utf-8") as f:
    f.write(m1_01)
with open(os.path.join(CONTENT_DIR, "m1_02_ml_paradigms.md"), "w", encoding="utf-8") as f:
    f.write(m1_02)
with open(os.path.join(CONTENT_DIR, "m1_03_parameter_estimation_mle.md"), "w", encoding="utf-8") as f:
    f.write(m1_03)

print("Module 1 topics 1-3 upgraded.")
